#!/bin/bash

# Toggle Mute
toggle_mute() {
	if [ "$(pamixer --get-mute)" == "false" ]; then
		pamixer -m
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		pamixer -u
	fi
}

# Execute accordingly
if [[ "$1" == "--toggle" ]]; then
	toggle_mute
fi
